service: issue-serverless-rest-api

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-northeast-2
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  createIssue:
    handler: issue/create.create
    events:
      - http:
          path: issue
          method: post
          cors: true

  listIssue:
    handler: issue/list.list
    events:
      - http:
          path: issue
          method: get
          cors: true

  getIssue:
    handler: issue/get.get
    events:
      - http:
          path: issue/{id}
          method: get
          cors: true

  updateIssue:
    handler: issue/update.update
    events:
      - http:
          path: issue/{id}
          method: put
          cors: true

  deleteIssue:
    handler: issue/delete.delete
    events:
      - http:
          path: issue/{id}
          method: delete
          cors: true

  auth:
    handler: auth/auth.authorize

  publicEndpoint:
    handler: auth/handler.publicEndpoint
    events:
      - http:
          path: auth/public
          method: get
          integration: lambda
          cors: true

  privateEndpoint:
    handler: auth/handler.privateEndpoint
    events:
      - http:
          path: auth/private
          method: get
          authorizer: auth
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token

  create:
    handler: todos/create.create
    events:
      - http:
          path: todos
          method: post
          cors: true

  list:
    handler: todos/list.list
    events:
      - http:
          path: todos
          method: get
          cors: true

  get:
    handler: todos/get.get
    events:
      - http:
          path: todos/{id}
          method: get
          cors: true

  update:
    handler: todos/update.update
    events:
      - http:
          path: todos/{id}
          method: put
          cors: true

  delete:
    handler: todos/delete.delete
    events:
      - http:
          path: todos/{id}
          method: delete
          cors: true

resources:
  Resources:
    TodosDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}

